safe: true # Required for GitHub Pages
lsi: false # Required for GitHub Pages
pygments: true # Required for GitHub Pages

kramdown:
  input: GFM

defaults:
  -
    scope:
      path: "docs"
      type: "pages"
    values:
      layout: "default"