safe: true # Required for GitHub Pages
lsi: false # Required for GitHub Pages
highlighter: rouge # Required for GitHub Pages

kramdown:
  input: GFM

defaults:
  -
    scope:
      path: "Docs"
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: "Docs/ModInstaller"
      type: "pages"
    values:
      layout: "default"
      categories: "ModInstaller"
  -
    scope:
      path: "Docs/ServerInstaller"
      type: "pages"
    values:
      layout: "default"
      categories: "ServerInstaller"
  -
    scope:
      path: "Docs/SiteTester"
      type: "pages"
    values:
      layout: "default"
      categories: "SiteTester"
  -
    scope:
      path: "Docs/DatabaseSearcher"
      type: "pages"
    values:
      layout: "default"
      categories: "DatabaseSearcher"
