safe: true # Required for GitHub Pages
lsi: false # Required for GitHub Pages
pygments: true # Required for GitHub Pages

kramdown:
  input: GFM

defaults:
  -
    scope:
      path: "Docs"
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: "Docs/ModInstaller"
      type: "pages"
    values:
      layout: "default"
      categories: "ModInstaller"